### PR TITLE
(*) replaced tabs with spaces; dont use tabs plz

### PR DESCRIPTION
**Pull request by korobkin**
Let's never use mixed tabs and spaces in python scripts. Only spaces
should be allowed, as described in this Python programming guide:
http://legacy.python.org/dev/peps/pep-0008/#tabs-or-spaces

I have replaced tabs with spaces in all these scripts, but now somebody should probably check if they still work. Wrong indentation in Python can cause very serious bugs, which are hard to find.

### CODE REVIEW

**Comment by fherwig** [comment]
@adam-paul @OClarkson @critter1 @swjones 
- develop some basic tests if the python tools are working
- apply to this branch
- @adam-paul merge pull request
- @adam-paul implement in travis-ci

**Comment by 2sn** [comment]
@fherwig @korobkin  with the new fixes I can now cleanly import the new branch.
As a result, a first very basic "test suite" we should create is to just import all modules ...

**Comment by korobkin** [comment]
@2sn @fherwig I am going to kill this branch to avoid confusion. This is now superseded by #5

**Comment by 2sn** [comment]
@korobkin - please check my version whether it seems OK to you.,

On 7 June 2016 at 09:08, korobkin notifications@github.com wrote:

> I am going to kill this branch to avoid confusion. This is now superseded
> by #3 https://github.com/NuGrid/NuGridPy/issues/3
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/NuGrid/NuGridPy/pull/2#issuecomment-224115993, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABNtFkhgZFsJcyNyrf_IFy5Cy4rGdb-eks5qJKh7gaJpZM4IoCPW
> .

## 

Sent from gmail.

**Pull request closed without merging**
