### PR TITLE
fix some parts for compatibility with python 3.  rename utils.py to n…

### PR DESCRIPTION
**Pull request by 2sn**
@swjones @fherwig @marcop46 
added some fixes for compatibility with python 3
utils was renamed to nuutils.py - name was too generic.
should use package for nugridpy instead (see issue #4)

### CODE REVIEW

**Comment by 2sn** [comment]
@fherwig @korobkin @marcop46 @critter1 @swjones 
the last update converts NuGridPy into a package.
It imports on both python2 and python3

I renamed `nuutils.py` back to `utils.py`, the name was too ridiculous.

``` shell
~/NuGrid>python
Python 3.5.1 (default, Apr 14 2016, 22:46:05) 
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from NuGridPy import *
>>> 
```

``` shell
~/NuGrid>python2
Python 2.7.11 (default, Mar 31 2016, 20:46:51) 
[GCC 5.3.1 20151207 (Red Hat 5.3.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from NuGridPy import *
>>> 
```

This will require some change in other packages that use NuGridPy but is a way to the future - allowing changes inside NuGridPy in a more transparent way while not polluting name space when used by other users (like myself).

So, in the future, you put the parent directory of NuGridPy into your PYTHONPATH and then use, e.g., utils as `from NuGridPy import utils as u` to to the way you did before

**\* I urge you to test and switch to this new version ***

**Comment by 2sn** [comment]
@korobkin - I think this now supercedes #2 - agreed?

**Comment by korobkin** [comment]
@2sn yes but... there are still some tabs in the rest of the files (astronomy.py, data_plot.py, nugridse.py) which are not corrected in this branch. And, we have three branches now.. I am confused.
Shall I try to incorporate all the commits from py3fix_alex into this branch to eliminate ambiguity?

**Comment by 2sn** [comment]
I since I added more fixes to my branch, and all tabs are gone, I thin it
supercedes your branch.

On 7 June 2016 at 08:49, korobkin notifications@github.com wrote:

> @2sn https://github.com/2sn yes but... there are plenty of tabs in the
> rest of the files (ascii_table.py, astronomy.py, dat_plot.py, grain.py,
> etc.) which are not corrected in this branch. And,we have three branches
> now.. I am confused.
> Shall I try to incorporate all the commits from py3fix_alex into this
> branch to eliminate ambiguity?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/NuGrid/NuGridPy/pull/5#issuecomment-224112705, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABNtFlf4lWyHct99dZICP2f0Q0zcXwK3ks5qJKQRgaJpZM4ItFU0
> .

## 

Sent from gmail.

**Comment by korobkin** [comment]
@2sn ok I deleted my branch.

**Comment by 2sn** [comment]
@korobkin - could you please check if my new branch works for you?

On 7 June 2016 at 09:15, korobkin notifications@github.com wrote:

> @2sn https://github.com/2sn ok I deleted my branch.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/NuGrid/NuGridPy/pull/5#issuecomment-224117235, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABNtFn-3K6xMtFY50VD69uYS2m-fipcyks5qJKokgaJpZM4ItFU0
> .

## 

Sent from gmail.

**Comment by korobkin** [comment]
@2sn works for me in both python2.7 and python3.

**Comment by korobkin** [comment]
@2sn also works on Mac, at least I can import all modules from NuGridPy without errors

**Comment by adam-paul** [comment]
I think from a modular perspective it would be best for the .py scripts to live in their own directory within the repo (e.g. scripts or nugridpy_scripts). This allows the PYTHONPATH to be more general for testing and for examples, and also removes the need for relative path imports (e.g. `from . import ...`) since these can sometimes become a nuisance if the directory structure changes in any significant manner at some time in the future. 

I've made these changes locally but let me know if there are any complaints before I push them.

**Comment by adam-paul** [comment]
@2sn 

as for testing with python2.7 and python3: all imports work for me with python2.7, but fail in python3.5 due to futurization issues (no `past` module, probably a problem with my local python build so I will continue looking into it).

However, I have a regression test for ppn.py and a few other scripts which is failing in both python2.7 and python3 and only on this branch -- it works fine from master. Attached is the error:

ppnerror

I'll try to fix this bug but if any obvious cause jumps out at you from what has been changed in this branch feel free to look into it!

**Comment by 2sn** [comment]
@adam-paul 
Please have a look at the README file, at the bottom, for required modules - those that I had to install extra.  Yes, you need to install the `future` module in python 3.5.

I know the imports work, but some of the keywords may not; I had to change the sorted function to the python 3 variety, this may require and extra import from bulidins of `sorted` to make it work in python 2.  this would be the case when loading se.h5 files.

**Comment by 2sn** [comment]
@adam-paul 
Can you send me the complete data code for this regression test?
You you can do a rebase of this branch to include the regression test?
Maybe most easy to just add the required files?
Probably not if there is data files involved, those should be dynamically created/downloaded and not be part of the git repository.

**Comment by 2sn** [comment]
@adam-paul 
the path in our error message shows a scripts subdirectory in nugridpy which is not part of the repo.

**Comment by 2sn** [comment]
@korobkin Thanks for all your updates and fixes!

**Comment by 2sn** [comment]
@adam-paul 
not sure I understand your comment on the scripts subdirectory, and w/r relative imports.  What scripts?

**Comment by 2sn** [comment]
@adam-paul @marcop46 
looking at the `_classTest(self)` method of `class DataPlot`, I assume the relative imports affect class name.  
Obviously, the what is done in this method is complete blunder.
1) use of `isinstance` would seem more appropriate if data plot knew about these other classes (would require import)
2) instead of a sequence of `elif` the use of a class-level dictionary would be much more efficient
3) the entire things should be refactored to use derived classes for variation in behaviour rather than testing the name of the derived class
4) the file name of the derived class is also hard-coded ... (!)
5) for the time being a hot fix would be just use the tail of the class name, e.g., something like

``` python
c='.'.join(str(self.__class__)[:-2].rsplit('.', 2)[-2:])
```

But I do need test data for this

**Comment by fherwig** [comment]
Sorry guys - have not been able to fully follow this in detail enough. Re-assigned to @korobkin so that this can move forward. @adam-paul - are you able to test on this branch?

**Comment by adam-paul** [comment]
@2sn
Great, thank you for looking into this! 

Regarding scripts/subdirectories, I was just advocating for an organizational scheme in which the .py files are separated from the rest of the repo in their own subdirectory, and I will have a regression-tests subdirectory, and so on. Otherwise things could get quite cluttered. As for the relative imports (things like `from . import ...` and `import .utils`), they have been giving me trouble when I try to import the .py files from anywhere but the directory they are located in, even with the path variable set there. My understanding was that these are for special cases and should be avoided usually?

I will also make a new branch from this one which includes parts of the regression test suite I am building (only some of it is working so I will only include those bits which are) and some test data!

@fherwig 
Yes testing is ongoing on this branch, should hopefully be able to merge pretty quickly here.

**Comment by 2sn** [comment]
@adam-paul @korobkin 

### Please no unnecessary subdirectories

If you nest things too deep you will have yo make import in the `__init__.py` file that could cause overhead, or people need to specify too dee module paths.
From what you write it is not clear to me why the relative imports cause you issues.  I have the impression you may not fully embrace the module concepts.  You should not import  routines locally, e.g., by being in the module directory.  Instead, you need the module or import scripts with full module path.  I would not nest things deeper at this time, by making NuGridPy a module we effectively already moved everything one level up.  **You would no longer put `NuGridPy` in your python path, but its parent directory!**  Based on my current structure, you then import utils as

``` python
from NuGridPy import utils
```

the same way you do

``` python
from numpy import pyplot as plt
```

if you were not to put utils.py in a `scipts` subdirectory that would have to become

``` python
from NuGridPy.scripts import utils
```

or

``` python
from NuGridPy.scripts.data_plot import DataPlot
```

I do not think we need this extra level.  Therefore I urge, please do not put the python files in an extra subdirectory.

Importing submodules like `utils` from a `scripts` subdirectory in `__init__.py` is possible but rather inefficient since the imported things all have to initialised **all the time**, even if not used.

@adam-paul 
Where I do agree is to put the test suite in a submodule (with its own `__init__.py`, e.g., named `test`).  There could also be an `examples` subdirectory, and in the long run, some of the current packages like `data_plot` may well become submodules to allow better code organisation, but using `__init__.py` in that submulde with the name of the current package can make such a transition transparent to the user.

@fherwig @swjones 
What we need now is to make `NuGridPy` a package (as in this branch) and users to use it in that way.

**Comment by 2sn** [comment]
@adam-paul 
BTW: did my fix https://github.com/NuGrid/NuGridPy/pull/5/commits/18a6784eea4f18dc274d3d799560b33be23af8bf work?

**Comment by adam-paul** [comment]
@2sn 
Noted! I will revert some of those subdirectory changes and continue to investigate why the relative imports might not be working for me. Once I get that working I'll let you know if your latest commit worked!

**Comment by adam-paul** [comment]
@2sn 
Yes, my issue with relative imports was a silly one involving the parent directory: my NuGridPy directory is named nugridpy and so the imports were not working simply because of the case sensitivity..... this could be an issue if people don't name their directories NuGridPy (or manually rename them), but if they are cloning appropriately from GitHub then it shouldn't be a problem. 

In any case, your latest commit did indeed fix the problem! But a new bug has arisen:

tmperror

In this case `b` is an abu_vector but for some reason this is not being triggered in `_classTest`

**Comment by 2sn** [comment]
@adam-paul 
please try the following steps
1) remove `NuGridPy` from your PYTHONPATH but add its parent directory
2) make sure not to be in this directory or subdirectory when running python
3) use relative package imports as outlined above (e.g., for the `pyplot` subpackage from `matplotlib`)

## Example:

``` python
from NuGridPy import utils as u
```

4) subdirectories should become submodules with their own `__init__.py`

**Comment by 2sn** [comment]
@adam-paul 
I would need to get your data and test code.

@fherwig @sam @adam-paul 
We could create a separate `test-data` repro on github, maybe also a `testing` repo - this is not to pollute the main repo with historic data.  Such repos can later be discarded.

**Comment by 2sn** [comment]
@adam-paul @sam @fherwig 
I agree that the repo should be renamed to lower case - this would be a lot easier for most users and in line with naming for other packages commonly used.

**Comment by 2sn** [comment]
### bug report

@adam-paul 
for your bug report listing is seems your code is different now from my latest commit from yesterday.

``` python
class DataPlot(object):

    _classTest_data = {
        'ppm.yprofile': 'YProfile',
        'ascii_table.ascii_table': 'AsciiTable',
        'nugridse.se': 'se',
        'mesa.mesa_profile': 'mesa_profile',
        'mesa.star_log': 'mesa.star_log',
        'mesa.history_data': 'mesa.star_log',
        'ppn.xtime': 'xtime',
        'ppn.abu_vector': 'PPN',
        'starobs.plot': 'starobs',
        'grain.gdb': 'grain',
        }

    def _classTest(self):
        '''
        Determines what the type of class instance the subclass is, so
        we can dynamically determine the behaviour of methods.

        The data this method uses (_classTest_data) NEEDS to be
        modified if any names of files or classes are changed.

        TODO - The entire use of this class needs to be refactored to use
        derived classes instead.
        '''
        c = '.'.join(str(self.__class__)[:-2].rsplit('.', 2)[-2:])
        return self._classTest_data.get(c, '')
```

Could you please try (check out, merge) the recent version?
(my apologies I pressed the "close" button by accident)

**Comment by 2sn** [comment]
@korobkin 
When do you think can we merge with main branch?

**Comment by korobkin** [comment]
@2sn I can import all packages without errors, but I am not sure everything works yet. On the other hand, scripts that I tried didn't work in the old version either. @fherwig was mentioning that we need an extensive set of test suites... but maybe shall we can add them after the merger? If so, I can merge the branch now.

**Comment by 2sn** [comment]
@fherwig your thoughts?
@korobkin There will still be bugs, but other development can go on before it diverges and the test suite developed in parallel.  I will try to help out when issues arise.
@fherwig There will be a major change to users due to the new module structure of NuGridPy.

**Comment by fherwig** [comment]
Well, I guess you made a decision. I think its fine as long as we stay on it until we have

> @fherwig There will be a major change to users due to the new module structure of NuGridPy.

@2sn can you put some notes into the [nugridpy wiki](https://github.com/NuGrid/NuGridPy/wiki) how users should go about using nugridpy now? Some examples etc would be useful. I think that would be essential. 

We also need to figure out how to create releases, and updated sphinx documentation semiautomatically. @adam-paul and I had some discussion on this with @lsiemens who has some info on how to do that.

**Pull request merged**
